--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO postgres;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: matches_doublesgame; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matches_doublesgame (
    id bigint NOT NULL,
    team1_score integer NOT NULL,
    team2_score integer NOT NULL,
    winner integer,
    match_id bigint NOT NULL
);


ALTER TABLE public.matches_doublesgame OWNER TO postgres;

--
-- Name: matches_doublesgame_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matches_doublesgame ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matches_doublesgame_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matches_doublesmatch; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matches_doublesmatch (
    id bigint NOT NULL,
    date timestamp with time zone NOT NULL,
    season_id bigint,
    team1_player1_id bigint NOT NULL,
    team1_player2_id bigint NOT NULL,
    team2_player1_id bigint NOT NULL,
    team2_player2_id bigint NOT NULL,
    winner_1_id bigint,
    winner_2_id bigint
);


ALTER TABLE public.matches_doublesmatch OWNER TO postgres;

--
-- Name: matches_doublesmatch_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matches_doublesmatch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matches_doublesmatch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matches_singlesgame; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matches_singlesgame (
    id bigint NOT NULL,
    player1_score integer NOT NULL,
    player2_score integer NOT NULL,
    winner integer,
    match_id bigint NOT NULL
);


ALTER TABLE public.matches_singlesgame OWNER TO postgres;

--
-- Name: matches_singlesgame_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matches_singlesgame ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matches_singlesgame_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matches_singlesmatch; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matches_singlesmatch (
    id bigint NOT NULL,
    date timestamp with time zone NOT NULL,
    player1_id bigint NOT NULL,
    player2_id bigint NOT NULL,
    season_id bigint,
    winner_id bigint
);


ALTER TABLE public.matches_singlesmatch OWNER TO postgres;

--
-- Name: matches_singlesmatch_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matches_singlesmatch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matches_singlesmatch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: players_player; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.players_player (
    id bigint NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    alias character varying(100),
    gender character varying(100) NOT NULL,
    date_of_birth date,
    nationality character varying(2),
    photo character varying(100),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone
);


ALTER TABLE public.players_player OWNER TO postgres;

--
-- Name: players_player_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.players_player ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.players_player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: players_ranking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.players_ranking (
    id bigint NOT NULL,
    ranking integer NOT NULL,
    singles_matches_played integer NOT NULL,
    doubles_matches_played integer NOT NULL,
    doubles_victories integer NOT NULL,
    singles_victories integer NOT NULL,
    player_id bigint NOT NULL,
    season_id bigint NOT NULL
);


ALTER TABLE public.players_ranking OWNER TO postgres;

--
-- Name: players_ranking_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.players_ranking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.players_ranking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profiles_playerprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.profiles_playerprofile (
    user_ptr_id integer NOT NULL,
    player_id bigint NOT NULL
);


ALTER TABLE public.profiles_playerprofile OWNER TO postgres;

--
-- Name: profiles_refereeprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.profiles_refereeprofile (
    user_ptr_id integer NOT NULL
);


ALTER TABLE public.profiles_refereeprofile OWNER TO postgres;

--
-- Name: seasons_season; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.seasons_season (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    start_date date NOT NULL,
    end_date date NOT NULL,
    singles_points_for_win integer NOT NULL,
    singles_points_for_loss integer NOT NULL,
    doubles_points_for_win integer NOT NULL,
    doubles_points_for_loss integer NOT NULL
);


ALTER TABLE public.seasons_season OWNER TO postgres;

--
-- Name: seasons_season_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.seasons_season ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seasons_season_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Token	7	add_token
26	Can change Token	7	change_token
27	Can delete Token	7	delete_token
28	Can view Token	7	view_token
29	Can add Token	8	add_tokenproxy
30	Can change Token	8	change_tokenproxy
31	Can delete Token	8	delete_tokenproxy
32	Can view Token	8	view_tokenproxy
33	Can add doubles match	9	add_doublesmatch
34	Can change doubles match	9	change_doublesmatch
35	Can delete doubles match	9	delete_doublesmatch
36	Can view doubles match	9	view_doublesmatch
37	Can add doubles game	10	add_doublesgame
38	Can change doubles game	10	change_doublesgame
39	Can delete doubles game	10	delete_doublesgame
40	Can view doubles game	10	view_doublesgame
41	Can add singles match	11	add_singlesmatch
42	Can change singles match	11	change_singlesmatch
43	Can delete singles match	11	delete_singlesmatch
44	Can view singles match	11	view_singlesmatch
45	Can add singles game	12	add_singlesgame
46	Can change singles game	12	change_singlesgame
47	Can delete singles game	12	delete_singlesgame
48	Can view singles game	12	view_singlesgame
49	Can add player	13	add_player
50	Can change player	13	change_player
51	Can delete player	13	delete_player
52	Can view player	13	view_player
53	Can add ranking	14	add_ranking
54	Can change ranking	14	change_ranking
55	Can delete ranking	14	delete_ranking
56	Can view ranking	14	view_ranking
57	Can add season	15	add_season
58	Can change season	15	change_season
59	Can delete season	15	delete_season
60	Can view season	15	view_season
61	Can add PlayerProfile	16	add_playerprofile
62	Can change PlayerProfile	16	change_playerprofile
63	Can delete PlayerProfile	16	delete_playerprofile
64	Can view PlayerProfile	16	view_playerprofile
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	authtoken	token
8	authtoken	tokenproxy
9	matches	doublesmatch
10	matches	doublesgame
11	matches	singlesmatch
12	matches	singlesgame
13	players	player
14	players	ranking
15	seasons	season
16	profiles	playerprofile
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-05-21 06:42:25.494885+00
2	auth	0001_initial	2025-05-21 06:42:25.519638+00
3	admin	0001_initial	2025-05-21 06:42:25.529436+00
4	admin	0002_logentry_remove_auto_add	2025-05-21 06:42:25.536267+00
5	admin	0003_logentry_add_action_flag_choices	2025-05-21 06:42:25.54166+00
6	contenttypes	0002_remove_content_type_name	2025-05-21 06:42:25.553449+00
7	auth	0002_alter_permission_name_max_length	2025-05-21 06:42:25.559757+00
8	auth	0003_alter_user_email_max_length	2025-05-21 06:42:25.565923+00
9	auth	0004_alter_user_username_opts	2025-05-21 06:42:25.572137+00
10	auth	0005_alter_user_last_login_null	2025-05-21 06:42:25.578599+00
11	auth	0006_require_contenttypes_0002	2025-05-21 06:42:25.579838+00
12	auth	0007_alter_validators_add_error_messages	2025-05-21 06:42:25.585972+00
13	auth	0008_alter_user_username_max_length	2025-05-21 06:42:25.594467+00
14	auth	0009_alter_user_last_name_max_length	2025-05-21 06:42:25.600644+00
15	auth	0010_alter_group_name_max_length	2025-05-21 06:42:25.607135+00
16	auth	0011_update_proxy_permissions	2025-05-21 06:42:25.613163+00
17	auth	0012_alter_user_first_name_max_length	2025-05-21 06:42:25.619634+00
18	authtoken	0001_initial	2025-05-21 06:42:25.628556+00
19	authtoken	0002_auto_20160226_1747	2025-05-21 06:42:25.645432+00
20	authtoken	0003_tokenproxy	2025-05-21 06:42:25.649489+00
21	authtoken	0004_alter_tokenproxy_options	2025-05-21 06:42:25.653084+00
22	seasons	0001_initial	2025-05-21 06:42:25.65667+00
23	players	0001_initial	2025-05-21 06:42:25.66828+00
24	matches	0001_initial	2025-05-21 06:42:25.701218+00
25	profiles	0001_initial	2025-05-21 06:42:25.714562+00
26	profiles	0002_refereeprofile_remove_playerprofile_is_referee	2025-05-21 06:42:25.736427+00
27	sessions	0001_initial	2025-05-21 06:43:24.635343+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: matches_doublesgame; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.matches_doublesgame (id, team1_score, team2_score, winner, match_id) FROM stdin;
\.


--
-- Data for Name: matches_doublesmatch; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.matches_doublesmatch (id, date, season_id, team1_player1_id, team1_player2_id, team2_player1_id, team2_player2_id, winner_1_id, winner_2_id) FROM stdin;
\.


--
-- Data for Name: matches_singlesgame; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.matches_singlesgame (id, player1_score, player2_score, winner, match_id) FROM stdin;
\.


--
-- Data for Name: matches_singlesmatch; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.matches_singlesmatch (id, date, player1_id, player2_id, season_id, winner_id) FROM stdin;
\.


--
-- Data for Name: players_player; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.players_player (id, first_name, last_name, alias, gender, date_of_birth, nationality, photo, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: players_ranking; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.players_ranking (id, ranking, singles_matches_played, doubles_matches_played, doubles_victories, singles_victories, player_id, season_id) FROM stdin;
\.


--
-- Data for Name: profiles_playerprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.profiles_playerprofile (user_ptr_id, player_id) FROM stdin;
\.


--
-- Data for Name: profiles_refereeprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.profiles_refereeprofile (user_ptr_id) FROM stdin;
\.


--
-- Data for Name: seasons_season; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.seasons_season (id, name, description, start_date, end_date, singles_points_for_win, singles_points_for_loss, doubles_points_for_win, doubles_points_for_loss) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 64, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 16, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 27, true);


--
-- Name: matches_doublesgame_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.matches_doublesgame_id_seq', 1, false);


--
-- Name: matches_doublesmatch_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.matches_doublesmatch_id_seq', 1, false);


--
-- Name: matches_singlesgame_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.matches_singlesgame_id_seq', 1, false);


--
-- Name: matches_singlesmatch_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.matches_singlesmatch_id_seq', 1, false);


--
-- Name: players_player_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.players_player_id_seq', 1, false);


--
-- Name: players_ranking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.players_ranking_id_seq', 1, false);


--
-- Name: seasons_season_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seasons_season_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: matches_doublesgame matches_doublesgame_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches_doublesgame
    ADD CONSTRAINT matches_doublesgame_pkey PRIMARY KEY (id);


--
-- Name: matches_doublesmatch matches_doublesmatch_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches_doublesmatch
    ADD CONSTRAINT matches_doublesmatch_pkey PRIMARY KEY (id);


--
-- Name: matches_singlesgame matches_singlesgame_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches_singlesgame
    ADD CONSTRAINT matches_singlesgame_pkey PRIMARY KEY (id);


--
-- Name: matches_singlesmatch matches_singlesmatch_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches_singlesmatch
    ADD CONSTRAINT matches_singlesmatch_pkey PRIMARY KEY (id);


--
-- Name: players_player players_player_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.players_player
    ADD CONSTRAINT players_player_pkey PRIMARY KEY (id);


--
-- Name: players_ranking players_ranking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.players_ranking
    ADD CONSTRAINT players_ranking_pkey PRIMARY KEY (id);


--
-- Name: players_ranking players_ranking_player_id_season_id_f9718a1e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.players_ranking
    ADD CONSTRAINT players_ranking_player_id_season_id_f9718a1e_uniq UNIQUE (player_id, season_id);


--
-- Name: profiles_playerprofile profiles_playerprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profiles_playerprofile
    ADD CONSTRAINT profiles_playerprofile_pkey PRIMARY KEY (user_ptr_id);


--
-- Name: profiles_playerprofile profiles_playerprofile_player_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profiles_playerprofile
    ADD CONSTRAINT profiles_playerprofile_player_id_key UNIQUE (player_id);


--
-- Name: profiles_refereeprofile profiles_refereeprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profiles_refereeprofile
    ADD CONSTRAINT profiles_refereeprofile_pkey PRIMARY KEY (user_ptr_id);


--
-- Name: seasons_season seasons_season_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seasons_season
    ADD CONSTRAINT seasons_season_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: matches_doublesgame_match_id_9291e434; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matches_doublesgame_match_id_9291e434 ON public.matches_doublesgame USING btree (match_id);


--
-- Name: matches_doublesmatch_season_id_643b9e5b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matches_doublesmatch_season_id_643b9e5b ON public.matches_doublesmatch USING btree (season_id);


--
-- Name: matches_doublesmatch_team1_player1_id_e9cebfce; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matches_doublesmatch_team1_player1_id_e9cebfce ON public.matches_doublesmatch USING btree (team1_player1_id);


--
-- Name: matches_doublesmatch_team1_player2_id_ab14e756; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matches_doublesmatch_team1_player2_id_ab14e756 ON public.matches_doublesmatch USING btree (team1_player2_id);


--
-- Name: matches_doublesmatch_team2_player1_id_3601d9f9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matches_doublesmatch_team2_player1_id_3601d9f9 ON public.matches_doublesmatch USING btree (team2_player1_id);


--
-- Name: matches_doublesmatch_team2_player2_id_61573f4e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matches_doublesmatch_team2_player2_id_61573f4e ON public.matches_doublesmatch USING btree (team2_player2_id);


--
-- Name: matches_doublesmatch_winner_1_id_d6069aaf; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matches_doublesmatch_winner_1_id_d6069aaf ON public.matches_doublesmatch USING btree (winner_1_id);


--
-- Name: matches_doublesmatch_winner_2_id_bc6ea3a1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matches_doublesmatch_winner_2_id_bc6ea3a1 ON public.matches_doublesmatch USING btree (winner_2_id);


--
-- Name: matches_singlesgame_match_id_b9264cc6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matches_singlesgame_match_id_b9264cc6 ON public.matches_singlesgame USING btree (match_id);


--
-- Name: matches_singlesmatch_player1_id_8a60f7e0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matches_singlesmatch_player1_id_8a60f7e0 ON public.matches_singlesmatch USING btree (player1_id);


--
-- Name: matches_singlesmatch_player2_id_6b5c74f2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matches_singlesmatch_player2_id_6b5c74f2 ON public.matches_singlesmatch USING btree (player2_id);


--
-- Name: matches_singlesmatch_season_id_9eb098a2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matches_singlesmatch_season_id_9eb098a2 ON public.matches_singlesmatch USING btree (season_id);


--
-- Name: matches_singlesmatch_winner_id_66c6344e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX matches_singlesmatch_winner_id_66c6344e ON public.matches_singlesmatch USING btree (winner_id);


--
-- Name: players_ranking_player_id_946e5781; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX players_ranking_player_id_946e5781 ON public.players_ranking USING btree (player_id);


--
-- Name: players_ranking_season_id_a60d9596; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX players_ranking_season_id_a60d9596 ON public.players_ranking USING btree (season_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matches_doublesgame matches_doublesgame_match_id_9291e434_fk_matches_d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches_doublesgame
    ADD CONSTRAINT matches_doublesgame_match_id_9291e434_fk_matches_d FOREIGN KEY (match_id) REFERENCES public.matches_doublesmatch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matches_doublesmatch matches_doublesmatch_season_id_643b9e5b_fk_seasons_season_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches_doublesmatch
    ADD CONSTRAINT matches_doublesmatch_season_id_643b9e5b_fk_seasons_season_id FOREIGN KEY (season_id) REFERENCES public.seasons_season(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matches_doublesmatch matches_doublesmatch_team1_player1_id_e9cebfce_fk_players_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches_doublesmatch
    ADD CONSTRAINT matches_doublesmatch_team1_player1_id_e9cebfce_fk_players_p FOREIGN KEY (team1_player1_id) REFERENCES public.players_player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matches_doublesmatch matches_doublesmatch_team1_player2_id_ab14e756_fk_players_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches_doublesmatch
    ADD CONSTRAINT matches_doublesmatch_team1_player2_id_ab14e756_fk_players_p FOREIGN KEY (team1_player2_id) REFERENCES public.players_player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matches_doublesmatch matches_doublesmatch_team2_player1_id_3601d9f9_fk_players_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches_doublesmatch
    ADD CONSTRAINT matches_doublesmatch_team2_player1_id_3601d9f9_fk_players_p FOREIGN KEY (team2_player1_id) REFERENCES public.players_player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matches_doublesmatch matches_doublesmatch_team2_player2_id_61573f4e_fk_players_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches_doublesmatch
    ADD CONSTRAINT matches_doublesmatch_team2_player2_id_61573f4e_fk_players_p FOREIGN KEY (team2_player2_id) REFERENCES public.players_player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matches_doublesmatch matches_doublesmatch_winner_1_id_d6069aaf_fk_players_player_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches_doublesmatch
    ADD CONSTRAINT matches_doublesmatch_winner_1_id_d6069aaf_fk_players_player_id FOREIGN KEY (winner_1_id) REFERENCES public.players_player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matches_doublesmatch matches_doublesmatch_winner_2_id_bc6ea3a1_fk_players_player_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches_doublesmatch
    ADD CONSTRAINT matches_doublesmatch_winner_2_id_bc6ea3a1_fk_players_player_id FOREIGN KEY (winner_2_id) REFERENCES public.players_player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matches_singlesgame matches_singlesgame_match_id_b9264cc6_fk_matches_s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches_singlesgame
    ADD CONSTRAINT matches_singlesgame_match_id_b9264cc6_fk_matches_s FOREIGN KEY (match_id) REFERENCES public.matches_singlesmatch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matches_singlesmatch matches_singlesmatch_player1_id_8a60f7e0_fk_players_player_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches_singlesmatch
    ADD CONSTRAINT matches_singlesmatch_player1_id_8a60f7e0_fk_players_player_id FOREIGN KEY (player1_id) REFERENCES public.players_player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matches_singlesmatch matches_singlesmatch_player2_id_6b5c74f2_fk_players_player_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches_singlesmatch
    ADD CONSTRAINT matches_singlesmatch_player2_id_6b5c74f2_fk_players_player_id FOREIGN KEY (player2_id) REFERENCES public.players_player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matches_singlesmatch matches_singlesmatch_season_id_9eb098a2_fk_seasons_season_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches_singlesmatch
    ADD CONSTRAINT matches_singlesmatch_season_id_9eb098a2_fk_seasons_season_id FOREIGN KEY (season_id) REFERENCES public.seasons_season(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matches_singlesmatch matches_singlesmatch_winner_id_66c6344e_fk_players_player_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches_singlesmatch
    ADD CONSTRAINT matches_singlesmatch_winner_id_66c6344e_fk_players_player_id FOREIGN KEY (winner_id) REFERENCES public.players_player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: players_ranking players_ranking_player_id_946e5781_fk_players_player_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.players_ranking
    ADD CONSTRAINT players_ranking_player_id_946e5781_fk_players_player_id FOREIGN KEY (player_id) REFERENCES public.players_player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: players_ranking players_ranking_season_id_a60d9596_fk_seasons_season_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.players_ranking
    ADD CONSTRAINT players_ranking_season_id_a60d9596_fk_seasons_season_id FOREIGN KEY (season_id) REFERENCES public.seasons_season(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: profiles_playerprofile profiles_playerprofile_player_id_9e940875_fk_players_player_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profiles_playerprofile
    ADD CONSTRAINT profiles_playerprofile_player_id_9e940875_fk_players_player_id FOREIGN KEY (player_id) REFERENCES public.players_player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: profiles_playerprofile profiles_playerprofile_user_ptr_id_bd23a143_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profiles_playerprofile
    ADD CONSTRAINT profiles_playerprofile_user_ptr_id_bd23a143_fk_auth_user_id FOREIGN KEY (user_ptr_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: profiles_refereeprofile profiles_refereeprofile_user_ptr_id_c8b09856_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profiles_refereeprofile
    ADD CONSTRAINT profiles_refereeprofile_user_ptr_id_c8b09856_fk_auth_user_id FOREIGN KEY (user_ptr_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

