# Generated by Django 5.1.2 on 2025-07-14 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ranking', models.IntegerField(default=0)),
                ('singles_matches_played', models.IntegerField(default=0)),
                ('doubles_matches_played', models.IntegerField(default=0)),
                ('doubles_victories', models.IntegerField(default=0)),
                ('singles_victories', models.IntegerField(default=0)),
                ('player_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='profiles.playerprofile')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_rankings', to='seasons.season')),
            ],
            options={
                'unique_together': {('player_profile', 'season')},
            },
        ),
    ]
