# Generated by Django 5.1.2 on 2025-07-14 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('profiles', '0001_initial'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublesmatch',
            name='team1_player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubles_matches_team1_player1', to='profiles.playerprofile'),
        ),
        migrations.AddField(
            model_name='doublesmatch',
            name='team1_player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubles_matches_team1_player2', to='profiles.playerprofile'),
        ),
        migrations.AddField(
            model_name='doublesmatch',
            name='team2_player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubles_matches_team2_player1', to='profiles.playerprofile'),
        ),
        migrations.AddField(
            model_name='doublesmatch',
            name='team2_player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubles_matches_team2_player2', to='profiles.playerprofile'),
        ),
        migrations.AddField(
            model_name='doublesmatch',
            name='winner_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doubles_matches_won1', to='profiles.playerprofile'),
        ),
        migrations.AddField(
            model_name='doublesmatch',
            name='winner_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doubles_matches_won2', to='profiles.playerprofile'),
        ),
        migrations.AddField(
            model_name='doublesgame',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='matches.doublesmatch'),
        ),
        migrations.AddField(
            model_name='singlesmatch',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singles_matches_as_player1', to='profiles.playerprofile'),
        ),
        migrations.AddField(
            model_name='singlesmatch',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singles_matches_as_player2', to='profiles.playerprofile'),
        ),
        migrations.AddField(
            model_name='singlesmatch',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='singles_matches', to='seasons.season'),
        ),
        migrations.AddField(
            model_name='singlesmatch',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='singles_matches_won', to='profiles.playerprofile'),
        ),
        migrations.AddField(
            model_name='singlesgame',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singles_games', to='matches.singlesmatch'),
        ),
    ]
