server {
    server_name ttranking.juso-software.com;

    # Serve React frontend
    root ~/tt-ranking-system/frontend/dist;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /test {
        return 200 "Test endpoint for https://ttranking.juso-software.com";
    }

    # Serve assets correctly from "public/assets/"
    location /assets/ {
        root ~/tt-ranking-system/frontend/dist/;
        expires 6M;
    }

    # Serve media files (uploaded images, etc.) from the correct directory
    location /media/ {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Accept, Authorization, Content-Type';
        alias ~/tt-ranking-system/backend/media/;
        expires 6M;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }


    # Compress responses
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Proxy requests to Django backend
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # SSL Configuration (Managed by Certbot)
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/ttranking.juso-software.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ttranking.juso-software.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = ttranking.juso-software.com) {
        return 301 https://$host$request_uri;
    } # Managed by Certbot

    listen 80;
    server_name ttranking.juso-software.com;
    return 404; # Managed by Certbot
}
