# Generated by Django 5.1.2 on 2025-07-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='last_operation',
        ),
        migrations.RemoveField(
            model_name='refereeprofile',
            name='last_operation',
        ),
    ]
